# Resolve react_native_pods.rb with node to allow for hoisting

source 'https://github.com/CocoaPods/Specs.git'
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, '15.1'
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'LynxLiftsApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Define the path to react-native-maps
  rn_maps_path = '../node_modules/react-native-maps'

  # Add Google Maps dependencies
  pod 'GoogleMaps', :modular_headers => true
  pod 'Google-Maps-iOS-Utils', :modular_headers => true
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseAnalytics', :modular_headers => true
  pod 'GoogleAppMeasurement', :modular_headers => true 
  pod 'FirebaseMessaging', :modular_headers => true

  # Add react-native-maps dependencies
  pod 'react-native-maps', :path => rn_maps_path
  pod 'react-native-maps-generated', :path => rn_maps_path

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end